# Generated by Django 3.0.7 on 2020-06-10 21:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20200609_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditem',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
